apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowyourname-api
  namespace: knowyourname
  labels:
    app: knowyourname-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knowyourname-api
  template:
    metadata:
      labels:
        app: knowyourname-api
    spec:
      containers:
        - name: api
          image: acrknownamedevelopment.azurecr.io/knowyourname-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: connection-string
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/nameanalysis/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/nameanalysis/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: knowyourname-api-service
  namespace: knowyourname
spec:
  selector:
    app: knowyourname-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
