name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/KnowYourName.sln
    
    - name: Build
      run: dotnet build src/KnowYourName.sln --no-restore --configuration Release
    
    - name: Run unit tests
      run: dotnet test tests/unit-tests/KnowYourName.Tests/KnowYourName.Tests.csproj --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  load-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Locust
      run: |
        cd tests/load-tests
        pip install -r requirements.txt
    
    - name: Run load tests (smoke test)
      run: |
        cd tests/load-tests
        # Run a quick smoke test with minimal load
        locust --headless --users 5 --spawn-rate 1 --run-time 30s --host http://localhost:5000

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Playwright
      run: |
        cd tests/e2e-tests
        npm ci
        npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: |
        cd tests/e2e-tests
        npx playwright test
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: tests/e2e-tests/playwright-report/
        retention-days: 30
